#!/bin/sh /etc/rc.common

START=97
STOP=01

USE_PROCD=1
PROG="/usr/share/rakitanmanager/core-manager.sh"

start_service() {
	config_load "rakitanmanager"
	config_get enabled "cfg" "enabled" "0"
	
	if [ "$enabled" = "1" ]; then
		procd_open_instance
		procd_set_param command "$PROG" "-s"
		procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param term_timeout 60
		procd_close_instance
	fi
}

stop_service() {
	"$PROG" -k
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "rakitanmanager"
}