#!/bin/sh /etc/rc.common

START=97
STOP=01

USE_PROCD=1
PROG="/usr/share/rakitanmanager/core-manager.sh"

run_instance() {
	config_get enabled "cfg" enabled "0"
	if [ $enabled = "1" ]; then
		procd_open_instance "cfg"
		procd_set_param command "$PROG" "-s"
		procd_set_param respawn
		procd_set_param term_timeout 60
		procd_close_instance
	fi
}

start_service() {
	config_load "rakitanmanager"
	config_get enabled "cfg" enabled "0"
	if [ $enabled = "1" ]; then
		config_foreach run_instance
	fi
}

stop_service() {
	$PROG -k
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "rakitanmanager"
}